pipeline {
    agent any
    environment {
        JAVA_HOME = tool name: 'jdk-8', type: 'jdk'
    }
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    stages {
        stage ('SCM Checkout') {
            steps {
                sh 'ls -lrta'
                deleteDir()
                sh 'ls -lrta'
                checkout scm
                sh 'ls -lrta'
            }
        }
        stage ('Build') {
            steps {
                dir ("complete") {
                    sh 'ls -lrta'
                    sh '''
                        chmod 744 ./gradlew
                        ./gradlew clean build
                    '''
                    sh 'ls -lrta'
                }
            }
        }
    }
    post {
        always{
            echo "Cleaning Workspace"
            cleanWs()
        }
    }
}